FROM laravelphp/vapor:php81

ARG BUILD_DATE
ARG VCS_REF

LABEL org.opencontainers.created=$BUILD_DATE \
      org.opencontainers.revision=$VCS_REF \
      org.opencontainers.title="laravel vapor ci docker image" \
      org.opencontainers.image.description="Laravel Vapor Docker Environment for CI" \
      org.opencontainers.source="https://github.com/bogdankharchenko/vapor-ci" \
      org.opencontainers.vendor="Bogdan Kharchenko" 

RUN pecl install pcov
RUN docker-php-ext-enable pcov

ENV COMPOSER_NO_INTERACTION=1
ENV COMPOSER_ALLOW_SUPERUSER=1

COPY ./scripts ./scripts

RUN ./scripts/composer.sh

