FROM laravelphp/vapor:php80

ARG BUILD_DATE
ARG VCS_REF

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vendor="bogdankharchenko" \
      org.label-schema.name="vapor-ci" \
      org.label-schema.description="Laravel Vapor Docker Environment for CI" \
      org.label-schema.url="https://github.com/bogdankharchenko/vapor-ci"

RUN pecl install pcov
RUN docker-php-ext-enable pcov

ENV COMPOSER_NO_INTERACTION=1
ENV COMPOSER_ALLOW_SUPERUSER=1

COPY ./scripts ./scripts

RUN ./scripts/composer.sh

